import type {
  AssetReference,
  BehaviorBinding,
  SceneNode,
  SceneProject,
} from "@/core/scene/types";

import type { CodegenContext } from "@/runtime/adapter";

/**
 * Shared scene → three.js codegen for every exporter.
 *
 * Walks the SceneProject's node tree and emits one ES module body that
 * builds the equivalent THREE.Scene at runtime. Both the Vite and the
 * Standalone ESM emitters call this — only the surrounding scaffolding
 * (package.json, index.html, importmap, etc.) differs between them.
 *
 * Out of scope deliberately:
 *   - Helper nodes (grid, axes) — they're editor chrome, not user content.
 *     Emitted to `warnings` so the user knows they were filtered.
 *   - OrbitControls / TransformControls — runtime viewer, not editor.
 *   - Postprocessing (OutlinePass, etc.) — selection feedback only.
 *   - Behavior code — `generateBehaviorCode` is still a stub; behaviors are
 *     a Phase 3 concern. Emitter ignores `node.behaviors` for v1.
 */

export interface SceneCodegenInput {
  project: SceneProject;
  includeDevComments?: boolean;
  /**
   * Inject behavior code emission. Callers (ThreeAdapter.exportProject)
   * bind this to their own `generateBehaviorCode` so scene-codegen doesn't
   * need to import IRuntimeAdapter (avoids the circular dep and keeps the
   * codegen module engine-agnostic).
   *
   * Optional: legacy callers without behaviors still produce a valid
   * module — node.behaviors arrays are ignored (warned about as a
   * forward-compat measure in A6 once the loop is wired up).
   */
  generateBehaviorCode?: (binding: BehaviorBinding, ctx: CodegenContext) => string;
}

export interface SceneCodegenOutput {
  /** Body of `src/scene.ts` (or equivalent). Exports `buildScene(THREE,
   *  GLTFLoader)` returning `{ scene, camera }`. */
  sceneModuleSource: string;
  /** Asset references the emitted code actually loads at runtime — the
   *  caller copies these into the export's `assets/` directory. */
  referencedAssets: AssetReference[];
  /** Non-fatal notes (skipped helpers, fallback materials, etc.) so the
   *  outer ExportResult can pass them up. */
  warnings: string[];
}

const NODE_KINDS_EMITTED = new Set<SceneNode["type"]>([
  "group",
  "mesh",
  "light",
  "camera",
  "prefab_instance",
]);

export function generateSceneModule(input: SceneCodegenInput): SceneCodegenOutput {
  const { project, includeDevComments = false, generateBehaviorCode } = input;
  const warnings: string[] = [];
  const referenced = new Map<string, AssetReference>();

  const ctx: EmitContext = {
    indent: 1,
    lines: [],
    project,
    warnings,
    referenced,
    includeDevComments,
    currentNodeVar: "",
    generateBehaviorCode,
  };

  emitProlog(ctx);
  for (const rootId of project.scene.root_node_ids) {
    emitNode(ctx, rootId, "scene");
  }
  emitEpilog(ctx);

  return {
    sceneModuleSource: ctx.lines.join("\n") + "\n",
    referencedAssets: [...referenced.values()],
    warnings,
  };
}

export interface EmitContext {
  indent: number;
  lines: string[];
  project: SceneProject;
  warnings: string[];
  referenced: Map<string, AssetReference>;
  includeDevComments: boolean;
  currentNodeVar: string;
  generateBehaviorCode?: SceneCodegenInput["generateBehaviorCode"];
}

function push(ctx: EmitContext, line: string): void {
  if (line.length === 0) {
    ctx.lines.push("");
    return;
  }
  ctx.lines.push("  ".repeat(ctx.indent) + line);
}

export function pushBlock(ctx: EmitContext, text: string): void {
  // text lines start at column 0; prefix each with the current indent
  // (mirrors how push() already prefixes single lines).
  const indent = "  ".repeat(ctx.indent);
  for (const line of text.split("\n")) {
    ctx.lines.push(line.length === 0 ? "" : indent + line);
  }
}

function devComment(ctx: EmitContext, text: string): void {
  if (!ctx.includeDevComments) return;
  push(ctx, `// ${text}`);
}

function emitProlog(ctx: EmitContext): void {
  const indent = ctx.indent;
  ctx.indent = 0;
  // Generator outputs *plain JS* (no TypeScript-only syntax) so both the
  // Vite emitter (which would otherwise need a .ts file) and the
  // Standalone ESM emitter (zero-build, in-browser) can serve it
  // verbatim. JSDoc carries the type intent for TS users who open the
  // file in their IDE.
  push(ctx, `// Generated by lowcode-3d. Edit freely — re-export will overwrite.`);
  push(ctx, `import * as THREE from "three";`);
  push(ctx, `import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";`);
  push(ctx, ``);
  push(ctx, `/**`);
  push(ctx, ` * @typedef {Object} BuiltScene`);
  push(ctx, ` * @property {THREE.Scene} scene`);
  push(ctx, ` * @property {THREE.Camera} camera`);
  push(ctx, ` * @property {Map<string, THREE.Group>} templates`);
  push(ctx, ` * @property {Array<(dt: number) => void>} tickers`);
  push(ctx, ` * @property {Array<Function>} interactions`);
  push(ctx, ` */`);
  push(ctx, ``);
  push(ctx, `/** @returns {Promise<BuiltScene>} */`);
  push(ctx, `export async function buildScene() {`);
  ctx.indent = 1;
  push(ctx, `const scene = new THREE.Scene();`);
  push(ctx, `let camera = new THREE.PerspectiveCamera(50, 1, 0.1, 1000);`);
  push(ctx, `camera.position.set(4, 3, 4);`);
  push(ctx, `camera.lookAt(0, 0, 0);`);
  push(ctx, `const templates = new Map();`);
  push(ctx, `const tickers = [];`);
  push(ctx, `const interactions = [];`);
  push(ctx, `const loader = new GLTFLoader();`);
  push(ctx, ``);
  push(ctx, `async function loadAsset(id, url) {`);
  push(ctx, `  const existing = templates.get(id);`);
  push(ctx, `  if (existing) return existing;`);
  push(ctx, `  const gltf = await new Promise((resolve, reject) => {`);
  push(
    ctx,
    `    loader.load(url, (g) => resolve({ scene: g.scene }), undefined, (e) => reject(e));`,
  );
  push(ctx, `  });`);
  push(ctx, `  templates.set(id, gltf.scene);`);
  push(ctx, `  return gltf.scene;`);
  push(ctx, `}`);
  push(ctx, ``);
  ctx.indent = indent;
}

function emitEpilog(ctx: EmitContext): void {
  push(ctx, ``);
  push(ctx, `return { scene, camera, templates, tickers, interactions };`);
  ctx.indent = 0;
  push(ctx, `}`);
}

function emitNode(ctx: EmitContext, nodeId: string, parentVar: string): void {
  const node = ctx.project.scene.nodes[nodeId];
  if (!node) return;

  if (!NODE_KINDS_EMITTED.has(node.type)) {
    ctx.warnings.push(
      `skipped node "${node.name}" (${node.id}) — type "${node.type}" is editor chrome and not emitted in production exports`,
    );
    return;
  }

  const varName = sanitizeVarName(node.id);
  devComment(ctx, `SceneNode "${node.name}" (${node.id}) — type=${node.type}`);

  switch (node.data.type) {
    case "group":
      emitGroup(ctx, varName, node);
      break;
    case "mesh":
      emitMesh(ctx, varName, node);
      break;
    case "light":
      emitLight(ctx, varName, node);
      break;
    case "camera":
      emitCamera(ctx, varName, node);
      break;
    case "prefab_instance":
      emitPrefabInstance(ctx, varName, node);
      break;
  }

  ctx.currentNodeVar = varName;
  emitTransform(ctx, varName, node);
  emitMeta(ctx, varName, node);
  push(ctx, `${parentVar}.add(${varName});`);
  if (ctx.generateBehaviorCode) {
    for (const binding of node.behaviors) {
      const code = ctx.generateBehaviorCode(binding, {
        project: ctx.project,
        warnings: ctx.warnings,
        currentNodeVar: varName,
      });
      if (code) pushBlock(ctx, code);
    }
  }
  push(ctx, ``);

  for (const childId of node.children_ids) {
    emitNode(ctx, childId, varName);
  }
}

function emitGroup(ctx: EmitContext, varName: string, node: SceneNode): void {
  push(ctx, `const ${varName} = new THREE.Group();`);
  push(ctx, `${varName}.name = ${JSON.stringify(node.name)};`);
}

function emitMesh(ctx: EmitContext, varName: string, node: SceneNode): void {
  if (node.data.type !== "mesh") return;
  // v1 echoes the editor's placeholder cube (1×1 box, MeshStandardMaterial).
  // Mesh nodes referencing real geometry currently route through
  // prefab_instance instead — keep this branch faithful to what the editor
  // renders today so a save → export round-trip looks identical on screen.
  push(ctx, `const ${varName}_geom = new THREE.BoxGeometry(1, 1, 1);`);
  push(
    ctx,
    `const ${varName}_mat = new THREE.MeshStandardMaterial({ color: 0xcccccc, metalness: 0, roughness: 0.7 });`,
  );
  push(ctx, `const ${varName} = new THREE.Mesh(${varName}_geom, ${varName}_mat);`);
  push(ctx, `${varName}.name = ${JSON.stringify(node.name)};`);
  ctx.warnings.push(
    `mesh "${node.name}" exported as a placeholder cube — hand-authored geometry export is not implemented in v1`,
  );
}

function emitLight(ctx: EmitContext, varName: string, node: SceneNode): void {
  if (node.data.type !== "light") return;
  const data = node.data;
  const colorHex = JSON.stringify(data.color);
  const intensity = JSON.stringify(data.intensity);
  switch (data.light_kind) {
    case "ambient":
      push(
        ctx,
        `const ${varName} = new THREE.AmbientLight(${colorHex}, ${intensity});`,
      );
      break;
    case "directional":
      push(
        ctx,
        `const ${varName} = new THREE.DirectionalLight(${colorHex}, ${intensity});`,
      );
      if (data.cast_shadow) push(ctx, `${varName}.castShadow = true;`);
      break;
    case "point": {
      const distance = data.distance ?? 0;
      const decay = data.decay ?? 2;
      push(
        ctx,
        `const ${varName} = new THREE.PointLight(${colorHex}, ${intensity}, ${distance}, ${decay});`,
      );
      if (data.cast_shadow) push(ctx, `${varName}.castShadow = true;`);
      break;
    }
    case "spot": {
      const distance = data.distance ?? 0;
      const angle = data.angle ?? Math.PI / 3;
      const penumbra = data.penumbra ?? 0;
      const decay = data.decay ?? 2;
      push(
        ctx,
        `const ${varName} = new THREE.SpotLight(${colorHex}, ${intensity}, ${distance}, ${angle}, ${penumbra}, ${decay});`,
      );
      if (data.cast_shadow) push(ctx, `${varName}.castShadow = true;`);
      break;
    }
  }
  push(ctx, `${varName}.name = ${JSON.stringify(node.name)};`);
}

function emitCamera(ctx: EmitContext, varName: string, node: SceneNode): void {
  if (node.data.type !== "camera") return;
  const data = node.data;
  if (data.camera_kind === "perspective") {
    const fov = data.fov ?? 50;
    const aspect = data.aspect ?? 1;
    push(
      ctx,
      `const ${varName} = new THREE.PerspectiveCamera(${fov}, ${aspect}, ${data.near}, ${data.far});`,
    );
  } else {
    const left = data.left ?? -1;
    const right = data.right ?? 1;
    const top = data.top ?? 1;
    const bottom = data.bottom ?? -1;
    push(
      ctx,
      `const ${varName} = new THREE.OrthographicCamera(${left}, ${right}, ${top}, ${bottom}, ${data.near}, ${data.far});`,
    );
  }
  push(ctx, `${varName}.name = ${JSON.stringify(node.name)};`);
  // The first camera authored in the project becomes the active runtime
  // camera. Subsequent cameras land in the tree but the renderer ignores
  // them — same convention three.js editor uses.
  push(ctx, `camera = ${varName};`);
}

function emitPrefabInstance(ctx: EmitContext, varName: string, node: SceneNode): void {
  if (node.data.type !== "prefab_instance") return;
  const assetId = node.data.asset_id;
  const asset = ctx.project.assets.find((a) => a.id === assetId);
  if (!asset) {
    ctx.warnings.push(
      `prefab_instance "${node.name}" (${node.id}) references missing asset_id "${assetId}" — exported as empty group`,
    );
    push(ctx, `const ${varName} = new THREE.Group();`);
    push(ctx, `${varName}.name = ${JSON.stringify(node.name)};`);
    return;
  }
  ctx.referenced.set(asset.id, asset);
  const url = `./${asset.relative_path}`;
  push(
    ctx,
    `const ${varName}_tpl = await loadAsset(${JSON.stringify(asset.id)}, ${JSON.stringify(url)});`,
  );
  push(ctx, `const ${varName} = ${varName}_tpl.clone(true);`);
  push(ctx, `${varName}.name = ${JSON.stringify(node.name)};`);
}

function emitTransform(ctx: EmitContext, varName: string, node: SceneNode): void {
  const t = node.transform;
  push(
    ctx,
    `${varName}.position.set(${num(t.position[0])}, ${num(t.position[1])}, ${num(t.position[2])});`,
  );
  push(
    ctx,
    `${varName}.quaternion.set(${num(t.rotation[0])}, ${num(t.rotation[1])}, ${num(t.rotation[2])}, ${num(t.rotation[3])});`,
  );
  push(
    ctx,
    `${varName}.scale.set(${num(t.scale[0])}, ${num(t.scale[1])}, ${num(t.scale[2])});`,
  );
}

function emitMeta(ctx: EmitContext, varName: string, node: SceneNode): void {
  if (!node.visible) push(ctx, `${varName}.visible = false;`);
}

function num(n: number): string {
  if (Number.isInteger(n)) return n.toString();
  // 6 sig-figs is plenty for human-readable scene authoring and keeps file
  // diffs small. Trim trailing zeros.
  return parseFloat(n.toFixed(6)).toString();
}

const UNSAFE_VAR_CHARS = /[^a-zA-Z0-9_$]/g;

function sanitizeVarName(id: string): string {
  // Prefix with `n_` so a SceneNode id that happens to start with a digit
  // becomes a valid JS identifier. UUIDs use hyphens — replace with
  // underscores so we don't emit `n_abc-def`.
  const safe = id.replace(UNSAFE_VAR_CHARS, "_");
  return `n_${safe}`;
}
