import type { ExportFile, ExportResult, Exporter } from "@/runtime/adapter";
import type { SceneProject } from "@/core/scene/types";

import { generateSceneModule } from "./scene-codegen";

/**
 * Standalone ESM emitter — zero-build, drop into any static server and it
 * just runs.
 *
 * Layout:
 *   ├── index.html       ← importmap pointing three at esm.sh + canvas + boot
 *   ├── scene.js         ← scene-codegen output (plain JS)
 *   ├── main.js          ← renderer bootstrap, imports buildScene
 *   ├── README.md
 *   └── assets/
 *       └── <hash>.glb
 *
 * The importmap is what makes this build-free: `three` resolves to esm.sh
 * (same version as the editor) so we don't need a bundler. Caveat: needs
 * a static server (file:// won't work — browsers block module loading from
 * file URLs); README gives the user one-liners for python / npx serve.
 */

const THREE_CDN_VERSION = "0.184.0";

export const standaloneEsmEmitter: Exporter = {
  target: "standalone-esm",
  emit(project: SceneProject, options, generateBehaviorCode): ExportResult {
    const includeDevComments = options.include_dev_comments ?? false;
    const codegen = generateSceneModule({
      project,
      includeDevComments,
      generateBehaviorCode,
    });

    const files = new Map<string, ExportFile>();
    files.set("index.html", text(indexHtml(project)));
    files.set("scene.js", text(codegen.sceneModuleSource));
    files.set("main.js", text(mainJs(project, includeDevComments)));
    files.set("README.md", text(readme(project.metadata.name)));

    for (const asset of codegen.referencedAssets) {
      files.set(asset.relative_path, {
        kind: "asset_copy",
        source_relative_path: asset.relative_path,
      });
    }

    return { files, warnings: codegen.warnings };
  },
};

function text(content: string): ExportFile {
  return { kind: "text", content };
}

function indexHtml(project: SceneProject): string {
  const safeTitle = project.metadata.name.replace(/[<>&]/g, "");
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${safeTitle}</title>
    <style>
      html, body { margin: 0; padding: 0; height: 100%; background: #101418; }
      #app { width: 100vw; height: 100vh; display: block; }
    </style>
    <script type="importmap">
      {
        "imports": {
          "three": "https://esm.sh/three@${THREE_CDN_VERSION}",
          "three/examples/jsm/loaders/GLTFLoader.js": "https://esm.sh/three@${THREE_CDN_VERSION}/examples/jsm/loaders/GLTFLoader.js",
          "three/examples/jsm/controls/OrbitControls.js": "https://esm.sh/three@${THREE_CDN_VERSION}/examples/jsm/controls/OrbitControls.js"
        }
      }
    </script>
  </head>
  <body>
    <canvas id="app"></canvas>
    <script type="module" src="./main.js"></script>
  </body>
</html>
`;
}

function mainJs(project: SceneProject, includeDevComments: boolean): string {
  const lines: string[] = [];
  lines.push(`// Generated by lowcode-3d — standalone ESM target.`);
  lines.push(`import * as THREE from "three";`);
  lines.push(
    `import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";`,
  );
  lines.push(`import { buildScene } from "./scene.js";`);
  lines.push(``);
  if (includeDevComments) {
    lines.push(`// Bootstrap. Wire renderer + render loop + resize.`);
    lines.push(
      `// OrbitControls = drag to orbit, scroll to zoom. Edit to add postprocessing.`,
    );
  }
  lines.push(`const canvas = document.querySelector("#app");`);
  lines.push(
    `if (!canvas) throw new Error('missing <canvas id="app"> in index.html');`,
  );
  lines.push(``);
  lines.push(`const renderer = new THREE.WebGLRenderer({ canvas, antialias: true });`);
  lines.push(`renderer.setPixelRatio(window.devicePixelRatio);`);
  lines.push(`renderer.setClearColor(${JSON.stringify(backgroundColor(project))}, 1);`);
  lines.push(``);
  lines.push(`const built = await buildScene();`);
  lines.push(``);
  if (includeDevComments) {
    lines.push(`// Fallback ambient so a scene with no lights still shows something.`);
    lines.push(
      `// Intensity 0.3 — scenes with their own lighting won't be washed out.`,
    );
  }
  lines.push(`built.scene.add(new THREE.AmbientLight(0xffffff, 0.3));`);
  lines.push(``);
  lines.push(`const controls = new OrbitControls(built.camera, canvas);`);
  lines.push(`controls.enableDamping = true;`);
  lines.push(`controls.dampingFactor = 0.08;`);
  lines.push(``);
  lines.push(`// Event-driven behaviors (hover-highlight): set up once now that the`);
  lines.push(
    `// renderer + camera + canvas exist. Each setup binds its own listeners.`,
  );
  lines.push(
    `for (const setup of built.interactions) setup({ camera: built.camera, domElement: canvas });`,
  );
  lines.push(``);
  lines.push(`function resize() {`);
  lines.push(`  const w = canvas.clientWidth;`);
  lines.push(`  const h = canvas.clientHeight;`);
  lines.push(`  renderer.setSize(w, h, false);`);
  lines.push(`  if (built.camera instanceof THREE.PerspectiveCamera) {`);
  lines.push(`    built.camera.aspect = w / Math.max(1, h);`);
  lines.push(`    built.camera.updateProjectionMatrix();`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push(`resize();`);
  lines.push(`new ResizeObserver(resize).observe(canvas);`);
  lines.push(``);
  lines.push(`const clock = new THREE.Clock();`);
  lines.push(``);
  lines.push(`function tick() {`);
  lines.push(`  const dt = clock.getDelta();`);
  lines.push(`  for (const t of built.tickers) t(dt);`);
  lines.push(`  controls.update();`);
  lines.push(`  renderer.render(built.scene, built.camera);`);
  lines.push(`  requestAnimationFrame(tick);`);
  lines.push(`}`);
  lines.push(`tick();`);
  lines.push(``);
  return lines.join("\n");
}

function backgroundColor(project: SceneProject): string {
  const bg = project.settings.background;
  if (bg.kind === "color") return bg.color;
  return "#101418";
}

function readme(projectName: string): string {
  return `# ${projectName}

Generated by [lowcode-3d](https://github.com/longyi-xw/cd) — a zero-build three.js scene that runs from any static server.

## Run

The file uses ES module \`import\`s so opening \`index.html\` directly via file:// won't work — browsers refuse to load modules over file://. Pick one:

\`\`\`sh
# Python's built-in static server
python3 -m http.server 8000

# Node, no install
npx serve

# Any other static server you have lying around
\`\`\`

Then open the URL the server prints.

## Files

- \`index.html\` — importmap aliasing \`three\` to esm.sh, mounts the canvas.
- \`scene.js\` — generated scene graph (plain JS + JSDoc types).
- \`main.js\` — renderer bootstrap. Hand-edit to add OrbitControls etc.
- \`assets/\` — glTF binaries referenced by prefab instances.
`;
}
