import type { ExportFile, ExportResult, Exporter } from "@/runtime/adapter";
import type { SceneProject } from "@/core/scene/types";

import { generateSceneModule } from "./scene-codegen";

/**
 * Vite project emitter — produces a complete on-disk project the user can
 * iterate on with `pnpm install && pnpm dev`.
 *
 * Layout:
 *   ├── package.json
 *   ├── vite.config.ts
 *   ├── jsconfig.json
 *   ├── index.html
 *   ├── src/
 *   │   ├── main.js          ← bootstraps the renderer, calls buildScene()
 *   │   └── scene.js         ← generated by scene-codegen.ts (plain JS + JSDoc)
 *   └── assets/
 *       └── <hash>.glb       ← copied from <source-project>/assets/
 *
 * Plain-JS output: scene-codegen emits a JS module with JSDoc types
 * rather than a `.ts` file, so the same source serves the Standalone ESM
 * target too (no build step). Users who want TypeScript can rename to .ts
 * and add their own annotations — JSDoc carries enough intent for editors
 * to give them sensible inference.
 */

const THREE_VERSION = "^0.184.0";
const THREE_TYPES_VERSION = "^0.184.1";
const VITE_VERSION = "^5.4.21";

export const viteEmitter: Exporter = {
  target: "vite",
  emit(project: SceneProject, options): ExportResult {
    const includeDevComments = options.include_dev_comments ?? false;
    const codegen = generateSceneModule({ project, includeDevComments });

    const files = new Map<string, ExportFile>();
    const projectName = slugifyProjectName(project.metadata.name);

    files.set("package.json", text(packageJson(projectName)));
    files.set("vite.config.js", text(viteConfig()));
    files.set("jsconfig.json", text(jsconfig()));
    files.set("index.html", text(indexHtml(project.metadata.name)));
    files.set("src/scene.js", text(codegen.sceneModuleSource));
    files.set("src/main.js", text(mainJs(project, includeDevComments)));
    files.set("README.md", text(readme(project.metadata.name)));

    for (const asset of codegen.referencedAssets) {
      // The on-disk path inside the export mirrors the source project's
      // `relative_path` exactly (e.g. `assets/<hash>.glb`). The Rust write
      // side resolves `source_relative_path` against the source project
      // directory and hardlinks where possible.
      files.set(asset.relative_path, {
        kind: "asset_copy",
        source_relative_path: asset.relative_path,
      });
    }

    return { files, warnings: codegen.warnings };
  },
};

function text(content: string): ExportFile {
  return { kind: "text", content };
}

function packageJson(name: string): string {
  return (
    JSON.stringify(
      {
        name,
        private: true,
        version: "0.0.1",
        type: "module",
        scripts: {
          dev: "vite",
          build: "vite build",
          preview: "vite preview",
        },
        dependencies: {
          three: THREE_VERSION,
        },
        devDependencies: {
          "@types/three": THREE_TYPES_VERSION,
          vite: VITE_VERSION,
        },
      },
      null,
      2,
    ) + "\n"
  );
}

function viteConfig(): string {
  return `import { defineConfig } from "vite";

// Asset files (.glb / .gltf) live next to index.html and are served as-is.
// Bumping chunkSizeWarningLimit because three.js core is ~500 KB on its own
// — that's the cost of the library, not user-fixable.
export default defineConfig({
  build: {
    chunkSizeWarningLimit: 600,
  },
});
`;
}

function jsconfig(): string {
  // jsconfig.json gives VSCode + WebStorm type inference + import resolution
  // for the JSDoc-annotated source without forcing the user into a TS
  // toolchain. checkJs = true so JSDoc annotations are validated.
  return (
    JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          module: "ESNext",
          moduleResolution: "Bundler",
          checkJs: true,
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          lib: ["ES2022", "DOM", "DOM.Iterable"],
        },
        include: ["src/**/*"],
      },
      null,
      2,
    ) + "\n"
  );
}

function indexHtml(projectName: string): string {
  const safeTitle = projectName.replace(/[<>&]/g, "");
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${safeTitle}</title>
    <style>
      html, body { margin: 0; padding: 0; height: 100%; background: #101418; }
      #app { width: 100vw; height: 100vh; display: block; }
    </style>
  </head>
  <body>
    <canvas id="app"></canvas>
    <script type="module" src="/src/main.js"></script>
  </body>
</html>
`;
}

function mainJs(project: SceneProject, includeDevComments: boolean): string {
  const lines: string[] = [];
  lines.push(`// Generated by lowcode-3d. Edit freely — re-export will overwrite.`);
  lines.push(`import * as THREE from "three";`);
  lines.push(
    `import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";`,
  );
  lines.push(`import { buildScene } from "./scene.js";`);
  lines.push(``);
  if (includeDevComments) {
    lines.push(`// Bootstrap: get the canvas, wire renderer + resize, render loop.`);
    lines.push(`// OrbitControls = drag to orbit, scroll to zoom. Hand-edit to add`);
    lines.push(`// postprocessing or a different camera rig.`);
  }
  lines.push(`const canvas = document.querySelector("#app");`);
  lines.push(
    `if (!canvas) throw new Error('missing <canvas id="app"> in index.html');`,
  );
  lines.push(``);
  lines.push(`const renderer = new THREE.WebGLRenderer({ canvas, antialias: true });`);
  lines.push(`renderer.setPixelRatio(window.devicePixelRatio);`);
  lines.push(`renderer.setClearColor(${JSON.stringify(backgroundColor(project))}, 1);`);
  lines.push(``);
  lines.push(`const built = await buildScene();`);
  lines.push(``);
  if (includeDevComments) {
    lines.push(`// Fallback ambient so a scene with no lights still shows something.`);
    lines.push(
      `// Intensity is low (0.3) so scenes with their own lighting aren't washed out.`,
    );
  }
  lines.push(`built.scene.add(new THREE.AmbientLight(0xffffff, 0.3));`);
  lines.push(``);
  lines.push(`const controls = new OrbitControls(built.camera, canvas);`);
  lines.push(`controls.enableDamping = true;`);
  lines.push(`controls.dampingFactor = 0.08;`);
  lines.push(``);
  lines.push(`function resize() {`);
  lines.push(`  const w = canvas.clientWidth;`);
  lines.push(`  const h = canvas.clientHeight;`);
  lines.push(`  renderer.setSize(w, h, false);`);
  lines.push(`  if (built.camera instanceof THREE.PerspectiveCamera) {`);
  lines.push(`    built.camera.aspect = w / Math.max(1, h);`);
  lines.push(`    built.camera.updateProjectionMatrix();`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push(`resize();`);
  lines.push(`new ResizeObserver(resize).observe(canvas);`);
  lines.push(``);
  lines.push(`function tick() {`);
  lines.push(`  controls.update();`);
  lines.push(`  renderer.render(built.scene, built.camera);`);
  lines.push(`  requestAnimationFrame(tick);`);
  lines.push(`}`);
  lines.push(`tick();`);
  lines.push(``);
  return lines.join("\n");
}

function backgroundColor(project: SceneProject): string {
  const bg = project.settings.background;
  if (bg.kind === "color") return bg.color;
  // HDRI background is a runtime-loaded environment map — fall back to a
  // neutral dark clear color and let the user wire it up themselves.
  return "#101418";
}

function readme(projectName: string): string {
  return `# ${projectName}

Generated by [lowcode-3d](https://github.com/longyi-xw/lowcode-3d) — a self-contained Vite + three.js project.

## Run

\`\`\`sh
pnpm install
pnpm dev
\`\`\`

Open the URL Vite prints in a browser.

## Files

- \`src/scene.js\` — generated scene graph (plain JS + JSDoc types). Re-exporting from lowcode-3d overwrites this.
- \`src/main.js\` — renderer bootstrap. Hand-edit to add OrbitControls, postprocessing, etc.
- \`assets/\` — geometry assets referenced by prefab instances.
`;
}

const SLUG_RE = /[^a-z0-9-]+/g;

function slugifyProjectName(name: string): string {
  const slug = name
    .toLowerCase()
    .trim()
    .replace(SLUG_RE, "-")
    .replace(/^-+|-+$/g, "");
  return slug || "lowcode-3d-export";
}
