// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	saveProjectFolder: (path: string, files: { [key in string]: string }, overwrite: boolean) => typedError<null, FolderError>(__TAURI_INVOKE("save_project_folder", { path, files, overwrite })),
	openProjectFolder: (path: string) => typedError<{ [key in string]: string }, FolderError>(__TAURI_INVOKE("open_project_folder", { path })),
	getCurrentProjectPath: () => __TAURI_INVOKE<string | null>("get_current_project_path"),
	setCurrentProjectPath: (path: string | null) => __TAURI_INVOKE<void>("set_current_project_path", { path }),
	importGlbIntoProject: (sourcePath: string, projectPath: string) => typedError<ImportedAsset, FolderError>(__TAURI_INVOKE("import_glb_into_project", { sourcePath, projectPath })),
	/**
	 *  Returns the asset bytes as standard (RFC 4648) base64. Encoded rather than
	 *  the raw `Vec<u8>` because specta-generated bindings serialize byte vecs as
	 *  `number[]` — fine for tiny payloads, catastrophic for a 5 MB .glb (5M
	 *  JSON numbers, ~half a second of parse time). Base64 is ~33 % overhead +
	 *  O(N) encode/decode, but the bytes stay in compact-string form across the
	 *  IPC boundary.
	 */
	readProjectAsset: (projectPath: string, relativePath: string) => typedError<string, FolderError>(__TAURI_INVOKE("read_project_asset", { projectPath, relativePath })),
	writeExportFiles: (payload: ExportPayload) => typedError<ExportSummary, FolderError>(__TAURI_INVOKE("write_export_files", { payload })),
	setAiKey: (provider: AiProvider, key: string) => typedError<null, AiError>(__TAURI_INVOKE("set_ai_key", { provider, key })),
	hasAiKey: (provider: AiProvider) => typedError<boolean, AiError>(__TAURI_INVOKE("has_ai_key", { provider })),
	clearAiKey: (provider: AiProvider) => typedError<null, AiError>(__TAURI_INVOKE("clear_ai_key", { provider })),
	aiComplete: (req: AiCompleteRequest) => typedError<AiCompleteResponse, AiError>(__TAURI_INVOKE("ai_complete", { req })),
	testAiProvider: (provider: AiProvider, model: string) => typedError<null, AiError>(__TAURI_INVOKE("test_ai_provider", { provider, model })),
};

/* Types */
export type AiCompleteRequest = {
	provider: AiProvider,
	model: string,
	system: string,
	user: string,
	/**
	 *  JSON Schema as a string (frontend JSON.stringify). `serde_json::Value`
	 *  can't be exported to TS by specta, so JSON crosses the IPC boundary as
	 *  a string — same rationale as base64-for-bytes in assets.rs.
	 */
	json_schema: string | null,
};

export type AiCompleteResponse = {
	text: string | null,
	/**  Structured output as a JSON string (frontend JSON.parse). */
	json: string | null,
};

/**  与 FolderError 同款 specta 形状: { code, data? }。 */
export type AiError = { code: "no_key" } | { code: "network"; data: string } | { code: "api_error"; data: {
	status: number,
	message: string,
} } | { code: "parse"; data: string } | { code: "keychain"; data: string };

/**
 *  本期仅 Anthropic;加 provider = 加 enum 分支 + match 分支。
 *  lowercase 序列化 → "anthropic"，与前端 settings.aiProvider + keychain account 一致。
 */
export type AiProvider = "anthropic";

export type ExportPayload = {
	source_project_path: string,
	destination_path: string,
	text_files: { [key in string]: string },
	asset_copies: { [key in string]: string },
};

export type ExportSummary = {
	destination_path: string,
	text_file_count: number,
	asset_file_count: number,
};

export type FolderError = 
/**  std::io::Error wrapped with the path that triggered it. */
{ code: "io"; data: {
	path: string,
	message: string,
} } | 
/**  Target path exists but isn't a directory. */
{ code: "not_a_directory"; data: {
	path: string,
} } | 
/**
 *  Save target is a non-empty directory that doesn't look like a saved
 *  lowcode-3d project. Front-end should ask "overwrite?" and call again
 *  with `overwrite: true`.
 */
{ code: "already_exists_not_empty"; data: {
	path: string,
} } | 
/**
 *  Reserved for forwarding TS-side `PersistenceError` through the same
 *  error union so the UI has a single error shape to handle.
 */
{ code: "persistence"; data: {
	detail: string,
} };

export type ImportedAsset = {
	/**  Lowercase hex SHA-256 of the file bytes. */
	content_hash: string,
	/**
	 *  Project-relative POSIX path the file was written to (e.g.
	 *  `assets/<hash>.glb`).
	 */
	relative_path: string,
	/**
	 *  Basename of the source file (before any rename / hash mapping). The TS
	 *  side stores this in `AssetReference.source.original_filename` so the
	 *  editor can show the human name even though the on-disk file is opaque.
	 */
	original_filename: string,
	/**
	 *  File size in bytes — surfaced in the properties panel so a user
	 *  importing a 200 MB .glb gets visual feedback. Serialized as f64
	 *  (not u64) because specta forbids BigInt-style ints across the FFI
	 *  boundary; f64 is exact through 2^53, well above any plausible glTF
	 *  size.
	 */
	byte_length: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

