// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Smoke-test command so the binding-generation pipeline can be verified before
	 *  real I/O commands land in PR B2. Removable once `save_project_folder` /
	 *  `open_project_folder` exist.
	 */
	ping: () => __TAURI_INVOKE<string>("ping"),
};

